id: P3AC2D7ED
initial_creation_type: ocr
source_metadata:
  volumes:
    cf412b552e6d4c2dbcc272ff8bd4cd84:
      base_file: v040.txt
      image_group_id: I1PD95885
      title: འཇིགས་པ་བརྒྱད་ལས་སྐྱོབ་པ།
      total_pages: 1648
      volume_number: 40
